package com.inheritance;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Table(name = "cClientData")
@javax.persistence.Entity
public class cClientData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String cName;
	@org.kie.api.definition.type.Label("Surname")
	private java.lang.String cSurname;
	@org.kie.api.definition.type.Label("IdNumber")
	private java.lang.String cID;

	@javax.persistence.GeneratedValue(generator = "CCLIENTDATA_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "CCLIENTDATA_ID_GENERATOR", sequenceName = "CCLIENTDATA_ID_SEQ")
	private java.lang.Long id;

	public cClientData() {
	}

	public java.lang.String getcName() {
		return this.cName;
	}

	public void setcName(java.lang.String cName) {
		this.cName = cName;
	}

	public java.lang.String getcSurname() {
		return this.cSurname;
	}

	public void setcSurname(java.lang.String cSurname) {
		this.cSurname = cSurname;
	}

	public java.lang.String getcID() {
		return this.cID;
	}

	public void setcID(java.lang.String cID) {
		this.cID = cID;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public cClientData(java.lang.String cName, java.lang.String cSurname,
			java.lang.String cID, java.lang.Long id) {
		this.cName = cName;
		this.cSurname = cSurname;
		this.cID = cID;
		this.id = id;
	}

}